- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Check user name
  shell: whoami

- name: Lookup directory
  shell: pwd

- name: Build the ansible docker image
  docker_image:
    path: ansible
    name: ansible
    tag: v1