 ---
 
 - name: run the playbook tasks on the localhost
   hosts: 127.0.0.1
   connection: local
   remote_user: kevinwan
   become: yes
   tasks:

  - name: print out the hostname of target
    command: hostname
  
  - name: ensure aptitude is installed
    command: apt-get -y install aptitude
  
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt-get upgrade
    apt: upgrade=yes